CREATE TABLE MYDB.BATCHEMPLOYEE (EID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) , ENAME VARCHAR(30) NOT NULL);

SELECT * FROM MYDB.BATCHEMPLOYEE;

DELETE FROM MYDB.BATCHEMPLOYEE;